"""alterar_tabela_perfis

Revision ID: 55e39e52e4c1
Revises: afaf86d7e6fd
Create Date: 2025-01-11 16:07:29.213010

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55e39e52e4c1'
down_revision: Union[str, None] = 'afaf86d7e6fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('perfis', sa.Column('criado_em', sa.DateTime(), nullable=False))
    op.add_column('perfis', sa.Column('atualizado_em', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('perfis', 'atualizado_em')
    op.drop_column('perfis', 'criado_em')
    # ### end Alembic commands ###
