MENU_PRINCIPAL = """
=== MENU PRINCIPAL
=== ESCOLHA UMA DAS OPÇÕES ABAIXO
1. SAIR
2. GERENCIAR USUÁRIOS
3. GERENCIAR POSTAGENS
4. GERENCIAR CATEGORIAS
"""

MENU_USUARIOS = """
== MENU USUÁRIOS
== ESCOLHA UMA DAS OPÇÕES ABAIXO
1. VOLTAR AO MENU PRINCIPAL
2. SELECIONAR USUÁRIO(S)
3. INSERIR USUÁRIO
4. MODIFICAR USUÁRIO
5. APAGAR USUÁRIO
"""